export const studyTimerThemes = [
  {
    key: "classic",
    name: "Classic",
    icon: "⭐",
    background: "#FFF0D1",
    text: "#665039",
    primary: "#D6A04A",
    highlight: "#F4D68E",
    motif: "stars",
  },
  {
    key: "night",
    name: "Night",
    icon: "🌙",
    background: "#E9E5F6",
    text: "#39344F",
    primary: "#8A80B6",
    highlight: "#C4B6E5",
    motif: "crescent",
  },
  {
    key: "nature",
    name: "Nature",
    icon: "🍃",
    background: "#E4F0D9",
    text: "#31533B",
    primary: "#78A66B",
    highlight: "#BCD5A6",
    motif: "leaves",
  },
  {
    key: "sunset",
    name: "Sunset",
    icon: "🌅",
    background: "#FFE0D1",
    text: "#793E43",
    primary: "#DF806B",
    highlight: "#F5B384",
    motif: "sun-rays",
  },
  {
    key: "ocean",
    name: "Ocean",
    icon: "🌊",
    background: "#DCEFF5",
    text: "#25536B",
    primary: "#69AFC1",
    highlight: "#A9D8DD",
    motif: "waves",
  },
  {
    key: "floral",
    name: "Floral",
    icon: "🌸",
    background: "#F8C8D3",
    text: "#781A3B",
    primary: "#C94361",
    highlight: "#E9AE55",
    motif: "flowers",
  },
  {
    key: "butterflies",
    name: "Butterflies",
    icon: "🦋",
    background: "#F1DFF0",
    text: "#68426B",
    primary: "#B57DB8",
    highlight: "#E7A9C8",
    motif: "butterflies",
  },
  {
    key: "programmer",
    name: "Programmer",
    icon: "💻",
    background: "#E3EFE7",
    text: "#355549",
    primary: "#6C9B80",
    highlight: "#A6C8A9",
    motif: "code",
  },
  {
    key: "cyberpunk",
    name: "Cyberpunk",
    icon: "⚡",
    background: "#F1DDF0",
    text: "#63385F",
    primary: "#C45CA9",
    highlight: "#E88CC4",
    motif: "lightning",
  },
  {
    key: "golden-luxury",
    name: "Golden Luxury",
    icon: "💎",
    background: "#F5E8C8",
    text: "#604820",
    primary: "#B78E42",
    highlight: "#E5C878",
    motif: "diamonds",
  },
  {
    key: "ice-crystal",
    name: "Ice Crystal",
    icon: "❄️",
    background: "#DDF0FA",
    text: "#205579",
    primary: "#6AA8D0",
    highlight: "#A9D8EC",
    motif: "ice-crystals",
  },
  {
    key: "volcanic",
    name: "Volcanic",
    icon: "🔥",
    background: "#F6D9D0",
    text: "#71372F",
    primary: "#C95F48",
    highlight: "#E99B5B",
    motif: "flames",
  },
  {
    key: "matrix",
    name: "Matrix",
    icon: "🟢",
    background: "#DDF0DE",
    text: "#27513A",
    primary: "#529566",
    highlight: "#91C58E",
    motif: "matrix",
  },
  {
    key: "desert-storm",
    name: "Desert Storm",
    icon: "🏜️",
    background: "#F0DFC3",
    text: "#715334",
    primary: "#BD8A50",
    highlight: "#DDB978",
    motif: "desert",
  },
  {
    key: "blood-moon",
    name: "Blood Moon",
    icon: "🌕",
    background: "#F2D5D9",
    text: "#692838",
    primary: "#B14C5D",
    highlight: "#D48783",
    motif: "crescent",
  },
  {
    key: "formula-1",
    name: "Formula 1",
    icon: "🏎️",
    background: "#EEDDDD",
    text: "#5F2930",
    primary: "#BD4750",
    highlight: "#D78279",
    motif: "racing-squares",
  },
  {
    key: "pit-stop",
    name: "Pit Stop",
    icon: "🧰",
    background: "#E3E9E8",
    text: "#344E53",
    primary: "#A56E41",
    highlight: "#D9A35D",
    motif: "tools",
  },
  {
    key: "war-room",
    name: "War Room",
    icon: "🎯",
    background: "#EBEAD7",
    text: "#4D5038",
    primary: "#8C8B50",
    highlight: "#BCB477",
    motif: "targets",
  },
  {
    key: "fireworks",
    name: "Fireworks",
    icon: "🎆",
    background: "#EAE3F5",
    text: "#493B69",
    primary: "#A36BB4",
    highlight: "#DE95AE",
    motif: "fireworks",
  },
  {
    key: "carnival-chaos",
    name: "Carnival Chaos",
    icon: "🎪",
    background: "#FFE4D5",
    text: "#703D61",
    primary: "#D56E75",
    highlight: "#F0BA52",
    motif: "carnival",
  },
] as const;

export type StudyTimerTheme = (typeof studyTimerThemes)[number];
export type StudyTimerThemeKey = StudyTimerTheme["key"];

export function getStudyTimerTheme(
  key: string,
): StudyTimerTheme | null {
  return studyTimerThemes.find((theme) => theme.key === key) ?? null;
}